import {
  gray as _gray,
  red as _red,
  amber,
  emerald,
  blue as _blue,
  indigo as _indigo,
  violet,
  pink as _pink,
  black as _black,
  white as _white,
} from 'tailwindcss/colors';

/** @type {import('tailwindcss').Config} */
// eslint-disable-next-line @typescript-eslint/no-var-requires
const withMT = require('@material-tailwind/react/utils/withMT');
module.exports = withMT({
  content: [
    './node_modules/flowbite-react/**/*.{js,ts,jsx,tsx,mdx}',
    './node_modules/@material-tailwind/react/components/**/*.{js,ts,jsx,tsx}',
    './node_modules/@material-tailwind/react/theme/components/**/*.{js,ts,jsx,tsx}',
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: '1rem',
      },
    },
    
    fontSize: {
      xs:'0.7rem',
      sm: '0.8rem',
      base: '1rem',
      md: '1.1rem',
      lg: '1.15rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.9rem',
      '4xl': '2.1rem',
      '5xl': '2.6rem',
      '6xl': '3.75rem',
      '7xl': '4.5rem',
      '8xl':  '6rem',
      '9xl':  '8rem',
    },
    screens: {
      xs: '320px',
      sm: '576px',
      md: '768px',
      lg: '992px',
      xl: '1200px',
      xxl: '1650px',
    },

    extend: {
      lineClamp: {
        7: '7',
        8: '8',
        9: '9',
        10: '10',
      },
      scale: {
        140: '1.40',
        175: '1.75',
        200: '2',
        220: '2.20',
        250: '2.50',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'black-gradient': 'linear-gradient(90deg, rgba(0,0,0,0.8) 0%, rgba(0,0,0,1) 100%)',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'hero-pattern': '',
      },
      fontFamily: {
        philosopher: ['var(--font-philosopher)'],
        noto: ['var(--font-noto-sans-arabic)'],
        myriad: ['Myriad Pro', 'sans-serif'],
        segoe: ['Segoe UI', 'sans-serif'],
      },
    },
    colors: {
      primary: '#00B4D1',
      secondary: '#C40D3C',
      secondary_light: '#F9A539',
      grey_dark: '#4F4F4F',
      transparent: 'transparent',
      current: 'currentColor',
      default: '#0091ac',
      second: '#f7991e',
      softBeige:'#F0EFEF',
      lightBlack:'#222222',
      lightGray:'#5048487a',
      calendar:'#e9e9e9',
      warm: '#F9F6F6',
      biege: '#E6E6E6',
      opacityBlack:'rgba(0,0,0,0.9)',
      lightBiege: '#e9e9e9',
      softBlack:'#686868',
      title:'#424242',
      description:'#686868',
      darkHeader:'#191919',
      lightCyan: '#c9eaf0',
      darkCyan: '#00a5c6',
      pearl:'#e7e7e7',
      gray: _gray,
      red: _red,
      yellow: amber,
      green: emerald,
      blue: _blue,
      indigo: _indigo,
      purple: violet,
      pink: _pink,
      black: _black,
      white: _white,
    },
  },
  plugins: ['prettier-plugin-tailwindcss', require('flowbite/plugin')],
});
